"""Phase 1: Semantic Parser.

Deterministic parsing of the 1993 Doom status-bar face (``STF...``) lump
naming convention, as generated by ``ST_updateFaceWidget`` in the original
``st_stuff.c``: for each of the 5 health tiers there are 3 "straight ahead"
frames, one "turn right" frame, one "turn left" frame, an "ouch" (pain)
frame, an "evil grin" frame and a "rampage" (berserk kill) frame, plus two
health-tier-independent specials (god mode, dead).
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import Enum, IntEnum
from pathlib import Path
from typing import Callable

MIN_HEALTH_TIER = 0
MAX_HEALTH_TIER = 4


class Expression(str, Enum):
    STRAIGHT = "ST"
    OUCH = "OUCH"
    EVIL_GRIN = "EVL"
    KILL = "KILL"
    GOD = "GOD"
    DEAD = "DEAD"


class GazeDirection(IntEnum):
    CENTER = 0
    RIGHT = 1
    LEFT = 2


@dataclass(frozen=True, slots=True)
class FaceState:
    """Doom status-bar face state decoded from an ``STF...`` lump name."""

    expression: Expression
    health_tier: int
    gaze_direction: GazeDirection


class InvalidStfNameError(ValueError):
    """Raised when a filename does not match the STF naming convention."""


def _tier(match: re.Match[str]) -> int:
    return int(match.group("tier"))


def _build_straight(match: re.Match[str]) -> FaceState:
    return FaceState(Expression.STRAIGHT, _tier(match), GazeDirection.CENTER)


def _build_turn_right(match: re.Match[str]) -> FaceState:
    return FaceState(Expression.STRAIGHT, _tier(match), GazeDirection.RIGHT)


def _build_turn_left(match: re.Match[str]) -> FaceState:
    return FaceState(Expression.STRAIGHT, _tier(match), GazeDirection.LEFT)


def _build_ouch(match: re.Match[str]) -> FaceState:
    return FaceState(Expression.OUCH, _tier(match), GazeDirection.CENTER)


def _build_evil_grin(match: re.Match[str]) -> FaceState:
    return FaceState(Expression.EVIL_GRIN, _tier(match), GazeDirection.CENTER)


def _build_kill(match: re.Match[str]) -> FaceState:
    return FaceState(Expression.KILL, _tier(match), GazeDirection.CENTER)


def _build_god(match: re.Match[str]) -> FaceState:
    return FaceState(Expression.GOD, MIN_HEALTH_TIER, GazeDirection.CENTER)


def _build_dead(match: re.Match[str]) -> FaceState:
    return FaceState(Expression.DEAD, MIN_HEALTH_TIER, GazeDirection.CENTER)


_TIER_GROUP = "(?P<tier>[0-4])"

_PATTERNS: tuple[tuple[re.Pattern[str], Callable[[re.Match[str]], FaceState]], ...] = (
    (re.compile(rf"^STFST{_TIER_GROUP}[0-2]$"), _build_straight),
    (re.compile(rf"^STFTR{_TIER_GROUP}0$"), _build_turn_right),
    (re.compile(rf"^STFTL{_TIER_GROUP}0$"), _build_turn_left),
    (re.compile(rf"^STFOUCH{_TIER_GROUP}$"), _build_ouch),
    (re.compile(rf"^STFEVL{_TIER_GROUP}$"), _build_evil_grin),
    (re.compile(rf"^STFKILL{_TIER_GROUP}$"), _build_kill),
    (re.compile(r"^STFGOD0$"), _build_god),
    (re.compile(r"^STFDEAD0$"), _build_dead),
)


def parse_stf_filename(filename: str) -> FaceState:
    """Parse an ``STF...`` lump or sprite filename into its :class:`FaceState`.

    Accepts a bare lump name or a filesystem path with any extension
    (e.g. ``"STFST21.png"``, ``"STFGOD0"``); matching is case-insensitive
    on the stem but the convention itself is otherwise matched exactly.
    """
    stem = Path(filename).stem.upper()
    for pattern, build in _PATTERNS:
        match = pattern.match(stem)
        if match is not None:
            return build(match)
    raise InvalidStfNameError(f"{filename!r} is not a valid STF status-face name")


_STRAIGHT_FRAMES = 3


def iter_standard_stf_filenames() -> tuple[str, ...]:
    """The 42 canonical Doom STF face filenames, in ``ST_updateFaceWidget`` order."""
    names: list[str] = []
    for tier in range(MIN_HEALTH_TIER, MAX_HEALTH_TIER + 1):
        for frame in range(_STRAIGHT_FRAMES):
            names.append(f"STFST{tier}{frame}.png")
        names.append(f"STFTR{tier}0.png")
        names.append(f"STFTL{tier}0.png")
        names.append(f"STFOUCH{tier}.png")
        names.append(f"STFEVL{tier}.png")
        names.append(f"STFKILL{tier}.png")
    names.append("STFGOD0.png")
    names.append("STFDEAD0.png")
    return tuple(names)
